
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tuto_platform = { path = "../game", default-features = false }

[features]
default = ["tuto_platform/default"]
dylib-engine = ["tuto_platform/dylib-engine"]
