
[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
tuto_platform = { path = "../game", optional = true }

[features]
default = ["tuto_platform"]
dylib = ["fyrox/dylib"]
